### PR TITLE
Updated ReadMe

### PR DESCRIPTION
**Pull request by erika-tyagi**
Opening this up as a draft PR to collate my main questions so far:

**What do we want our directory structure to look like?** 
* I think it makes sense to (1) not include the folders that aren't Adult Facility Counts on GitHub, but (2) more clearly link to the Google Sheet in the ReadMe. Given that the files haven't been updated on GitHub in 4 months, I think that makes sense while we figure out which we want to integrate into our workflows and how to do that in the best way. 
* Longer-term, I like the idea of having folders for `latest-data`, `historical-data`, `facility-data`, and `population-data` maybe? I think centralizing our data makes sense to make it more accessible, and using submodules to separate code from data (like Neal set up for the scrapers) seems like it'll work? I can also see lots of arguments for other directory structures though, so would love to hear everyone else's thoughts! I also realize that changing folder names will break a lot of things (e.g. website, Google sheet, etc.) – so if it makes sense to do this, we should do it very carefully! 

**How do we feel about the lollipop chart and maps?** 
* My feelings won't be hurt if everyone hates them! I think it's useful to get a sense of what data we collect, but happy to delete them if others disagree! 

**I pulled most of the content from Hope's great historical-data ReadMe, but had a few questions:**
* Is it true that `Residents.Tadmin` is non-cumulative, but `Staff.Tested` is cumulative? I feel like `Residents.Tadmin` should be cumulative tests administered, but maybe I'm missing something?  
* Beyond adding the `LICENSE` file to the repo, is there anything else I have to do for the licensing? 

Very open to feedback on anything else, of course!

### CODE REVIEW

**Comment by erika-tyagi** [comment]
Note to self: delete `theme_map_behindbars` from the Rmd file if that gets merged into barstools.

**Comment by hjohns12** [comment]
> * I think it makes sense to (1) not include the folders that aren't Adult Facility Counts on GitHub, but (2) more clearly link to the Google Sheet in the ReadMe. Given that the files haven't been updated on GitHub in 4 months, I think that makes sense while we figure out which we want to integrate into our workflows and how to do that in the best way.

100% Agree!

> * Longer-term, I like the idea of having folders for `latest-data`, `historical-data`, `facility-data`, and `population-data` maybe? I think centralizing our data makes sense to make it more accessible, and using submodules to separate code from data (like Neal set up for the scrapers) seems like it'll work? I can also see lots of arguments for other directory structures though, so would love to hear everyone else's thoughts! I also realize that changing folder names will break a lot of things (e.g. website, Google sheet, etc.) – so if it makes sense to do this, we should do it very carefully!

Think we should discuss this as a group -- I'm torn on this. I don't like using sub-repos because they're so challenging to clone and I think they confuse external users. But I also appreciate how our separate data products get their own repos. 

> **How do we feel about the lollipop chart and maps?*

I wanna see them! 


> * Is it true that `Residents.Tadmin` is non-cumulative, but `Staff.Tested` is cumulative? I feel like `Residents.Tadmin` should be cumulative tests administered, but maybe I'm missing something?

Pretty sure that both are cumulative, but `Staff.Tested` is more ambiguous as to number of staff tested / staff tests administered. Should confirm this by looking more into the scraper code. 

> * Beyond adding the `LICENSE` file to the repo, is there anything else I have to do for the licensing?

Don't think so!

**Comment by nmmarquez** [comment]
This is amazing and I love the visuals. Im with you 100% about the restructuring of the folders and removing outdated folders I just want to be sure we make the other groups aware that we will now just be pointing directly to the google sheets data.

I love the maps and the lolichart plot they are fantastic. A note, some states technically provide some of the data we say they dont have but its is in such a unsable format that we cant scrape it. Two examples off the top of my head are CA facility specific testing data and all OK data for prisons. I also think we should also make the maps be explicitly for prisons. Also this changes a lot do we have a process for updating these files?

Residents.Tadmin should be cumulative as should Staff Tested but most pages having very weak documentation on who falls into the denominator for the staff tested category making that number tricky to interpret.

**Comment by erika-tyagi** [comment]
@nmmarquez 100% agreed about keeping other groups in the loop about what we're doing! I think we talked about asking Aaron about that during our meeting today too. 

@hjohns12 I also very much agree about the submodules being challenging and confusing. Looking forward to discussing later! And I think the best way to see the plots is [on the branch directly](https://github.com/uclalawcovid19behindbars/data/tree/readme)! 

@nmmarquez Re: update process, I had a few thoughts: (1) we manually re-run the script (maybe not every time we scrape, but every so often and caveat that the maps are subject to change), or (2) @hjohns12 leverages her GitHub wizardry to set up a similar CI to the historical data where it automatically re-runs every time we scrape if that's possible?  

And I agree that if we keep the maps, I should make it more clear that it's the state prison data that we collect – not necessarily what DOCs report, although those often go hand-in-hand. I'll update that and the  `Residents.Tadmin` definition.

**Comment by hjohns12** [comment]
I love the lollipop charts! And you guys know I <3 GH actions, happy to work on this

**Comment by erika-tyagi** [comment]
Per convo with @hjohns12: I think this is ready to merge for now unless we want to remove the non-Adult Facility Counts folders? Otherwise, we can figure out what to do with each of them after talking to the individual groups, either way works for me!

**Pull request closed without merging**
